// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqCtnsFWH31R9vwqc7CTIyhr9p-lQQSqQ',
    appId: '1:1045229711154:web:364384ba8aa3b76720712b',
    messagingSenderId: '1045229711154',
    projectId: 'devflow-f5d49',
    authDomain: 'devflow-f5d49.firebaseapp.com',
    storageBucket: 'devflow-f5d49.firebasestorage.app',
    measurementId: 'G-B1SSM3Y0BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-m9sQrwDiSb3bW0hqVjo30brsr5RAZQ',
    appId: '1:1045229711154:android:7f35424b5b3204e320712b',
    messagingSenderId: '1045229711154',
    projectId: 'devflow-f5d49',
    storageBucket: 'devflow-f5d49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0znrdNowT2ZNKK4uEFLHIt9M61AIvj4',
    appId: '1:1045229711154:ios:a88d17717260b93120712b',
    messagingSenderId: '1045229711154',
    projectId: 'devflow-f5d49',
    storageBucket: 'devflow-f5d49.firebasestorage.app',
    iosBundleId: 'com.example.devflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0znrdNowT2ZNKK4uEFLHIt9M61AIvj4',
    appId: '1:1045229711154:ios:a88d17717260b93120712b',
    messagingSenderId: '1045229711154',
    projectId: 'devflow-f5d49',
    storageBucket: 'devflow-f5d49.firebasestorage.app',
    iosBundleId: 'com.example.devflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqCtnsFWH31R9vwqc7CTIyhr9p-lQQSqQ',
    appId: '1:1045229711154:web:f76602d02206e2ef20712b',
    messagingSenderId: '1045229711154',
    projectId: 'devflow-f5d49',
    authDomain: 'devflow-f5d49.firebaseapp.com',
    storageBucket: 'devflow-f5d49.firebasestorage.app',
    measurementId: 'G-8721J4MRT2',
  );
}
